branches:
  only:
  - master
  - hookshot-replacement
before_install:
- sudo apt update
- sudo apt install software-properties-common
- sudo apt-add-repository --yes --update ppa:ansible/ansible
- sudo apt install -y ansible
- echo 'echo $SSH_PASSPHRASE' > ./dummy-askpass.sh
- chmod +x ./dummy-askpass.sh
addons:
  ssh_known_hosts: people.bocoup.com
script:
- eval "$(ssh-agent -s)"
- DISPLAY=1 SSH_ASKPASS=./dummy-askpass.sh ssh-add ./deploy/id_ed25519-robocoup-people.bocoup.com < /dev/null
- ansible-playbook deploy/ansible/deploy.yml --user robocoup --inventory=deploy/ansible/inventory/production
  -e "ansible_ssh_extra_args='-o StrictHostKeyChecking=no'"
