- name: Create well-known directory (used by ACME challenge)
  file:
    path: "{{site_path}}/.well-known"
    state: directory

- name: Determine whether Certbot has been initialized
  stat:
    path: /etc/letsencrypt/live/{{site_fqdn}}/fullchain.pem
  register: cert_file

- name: Initialize Certbot
  command: >
    certbot certonly --webroot --agree-tos --non-interactive
      {{ (env == 'production') | ternary('', '--test-cert') }}
      --email {{letsencrypt_email}}
      -w {{site_path}}
      -d {{site_fqdn}}
  when: cert_file.stat.exists == false
  notify: restart nginx

- name: Replace existing certificate with link to Certbot-issued certificate
  file:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    state: link
    # During initial provisioning, a self-signed certificate will be created so
    # nginx can run. The presence of those files necessitates the use of
    # "force" in this task.
    force: true
  with_items:
    - src: /etc/letsencrypt/live/{{site_fqdn}}/fullchain.pem
      dest: "{{ssl_cert_path}}"
    - src: /etc/letsencrypt/live/{{site_fqdn}}/privkey.pem
      dest: "{{ssl_key_path}}"
  when: cert_file.stat.exists == false

- name: Add cron job for certificate renewal
  cron:
    name: Certbot automatic renewal
    job: "/usr/bin/certbot renew --quiet --no-self-upgrade && service nginx reload"
    minute: 0
    hour: 23
